services:
  api:
    build:
      context: .   
      target: dev
    container_name: ha-sql-api
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USER: ${MYSQL_USER}
      DATABASE_PASSWORD: ${MYSQL_PASSWORD}
      DATABASE_NAME: ${MYSQL_DATABASE}
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/ha-sql-deliverable:cached  
      - /ha-sql-deliverable/node_modules
    

  db:
    image: mysql:latest
    container_name: ha-sql-api-db
    restart: unless-stopped
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE:    ${MYSQL_DATABASE}
      MYSQL_USER:        ${MYSQL_USER}
      MYSQL_PASSWORD:    ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  db_data:
